cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    gabi:
      email: rbriggs@gmail.com
      logged_in: false
      name: Ana Gabriela
      password: $2b$12$vX5N8Ma3IdjZ2MBihrjrS.VOXffh6p2NEmtbQIvhUUzomXlLuN7cO
    rafael:
      email: jsmith@gmail.com
      logged_in: true
      name: Rafael Fonseca
      password: $2b$12$vX5N8Ma3IdjZ2MBihrjrS.VOXffh6p2NEmtbQIvhUUzomXlLuN7cO
preauthorized:
  emails:
    - melsby@gmail.com
